server:
  # 项目端口
  port: 8080

spring:
  # thymeleaf相关
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    mode: HTML5
  # 数据库连接设置
  datasource:
    url: jdbc:mysql://localhost:3306/huidu_blog?serverTimezone=UTC&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    show-sql: false
    # 设置为当实体类改变则相应更新数据库表
    hibernate:
      ddl-auto: update
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 127.0.0.1:9300
  # 上传图片文件大小允许10MB以内
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

logging:
  # 日志打印级别
  level:
    root: info
    com.huidu.huidublog: debug
  # 生成日志的位置，更目录下的log文件中生成
  file: log/blog.log

# 评论人默认头像
comment.avatar: /images/avatar.png
# minio文件服务器相关信息
minio.minioUrl: http://localhost:9000
minio.username: OVPYT83F1W8MKGBMP5X3
minio.password: ZHysJLD+5NeFw38l9Td6kQ5v0t7n+8+RVp3rZBk7
minio.bucketName: blog